.. rst:group-schema:: axis

.. list-table::
   :widths: 20 15 20 45
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - ``TYPE``
     - attribute
     - character
     - literal ``'axis_t'``.
   * - ``REVISION``
     - attribute
     - integer
     - literal ``1``.
   * - ``label``
     - attribute
     - character
     - label.
   * - ``x``
     - dataset
     - real(:)
     - abscissa values.
