.. rst:group-schema:: axis

.. list-table::
   :widths: 15 10 10 65
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - :code:`TYPE`
     - attribute
     - character
     - literal :code:`'axis_t'`.
   * - :code:`REVISION`
     - attribute
     - integer
     - literal :code:`1`.
   * - :code:`label`
     - attribute
     - character
     - label.
   * - :code:`x`
     - dataset
     - real(:)
     - abscissa values.
