.. rst:group-schema:: limb

.. list-table::
   :widths: 15 10 10 65
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - :code:`TYPE`
     - attribute
     - character
     - literal :code:`'limb_t'`.
   * - :code:`REVISION`
     - attribute
     - integer
     - literal :code:`1`.
   * - :code:`law`
     - attribute
     - character
     - limb-darkening law (see the :ref:`limb-darkening-laws` section for a list of options).
       
