.. rst:group-schema:: limb

.. list-table::
   :widths: 20 15 20 45
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - ``TYPE``
     - attribute
     - character
     - literal ``'limb_t'``.
   * - ``REVISION``
     - attribute
     - integer
     - literal ``1``.
   * - ``law``
     - attribute
     - character
     - limb-darkening law (see :ref:`here <limb-darkening-laws>` for a list of options).
       
