.. rst:group-schema:: lin_range

.. list-table::
   :widths: 20 15 20 45
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - ``TYPE``
     - attribute
     - character
     - literal ``'lin_range_t'``.
   * - ``REVISION``
     - attribute
     - integer
     - literal ``1``.
   * - ``x_0``
     - attribute
     - real
     - abscissa start value.
   * - ``dx``
     - attribute
     - real
     - abscissa spacing.
   * - ``n``
     - attribute
     - integer
     - number of points.
