.. rst:group-schema:: lin_range

.. list-table::
   :widths: 15 10 10 65
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - :code:`TYPE`
     - attribute
     - character
     - literal :code:`'lin_range_t'`.
   * - :code:`REVISION`
     - attribute
     - integer
     - literal :code:`1`.
   * - :code:`x_0`
     - attribute
     - real
     - abscissa start value.
   * - :code:`dx`
     - attribute
     - real
     - abscissa spacing.
   * - :code:`n`
     - attribute
     - integer
     - number of points.
