.. rst:group-schema:: log_range

.. list-table::
   :widths: 15 10 10 65
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - :code:`TYPE`
     - attribute
     - character
     - literal :code:`'log_range_t'`.
   * - :code:`REVISION`
     - attribute
     - integer
     - literal :code:`1`.
   * - :code:`logx_0`
     - attribute
     - real
     - logarithm of abscissa start value.
   * - :code:`dlogx`
     - attribute
     - real
     - abscissa logarithmic spacing.
   * - :code:`n`
     - attribute
     - integer
     - number of points.
