.. rst:group-schema:: log_range

.. list-table::
   :widths: 20 15 20 45
   :header-rows: 1

   * - Item
     - Object Type
     - Data Type
     - Definition
   * - ``TYPE``
     - attribute
     - character
     - literal ``'log_range_t'``.
   * - ``REVISION``
     - attribute
     - integer
     - literal ``1``.
   * - ``logx_0``
     - attribute
     - real
     - logarithm of abscissa start value.
   * - ``dlogx``
     - attribute
     - real
     - abscissa logarithmic spacing.
   * - ``n``
     - attribute
     - integer
     - number of points.
